services:
  app:
    build: .
    container_name: ai-video-frame-app
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - ./uploads:/app/uploads
